@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": false,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 1,
    "backwardDepth": 1,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": false,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "No" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 0,
    "showDetailedClassStructure": true
  },
  "rootClass": "de.dhbw.karlsruhe.ase.application.PersistenceWriter",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
Game1052887806[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Game</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   loader: PersistenceReader [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   saver: PersistenceWriter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   state: GameState [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ build(plan: CraftingPlan): GameResult</TD></TR>
<TR><TD ALIGN="LEFT" >- checkLose()</TD></TR>
<TR><TD ALIGN="LEFT" >+ draw(): Card</TD></TR>
<TR><TD ALIGN="LEFT" >- endGameWith(result: GameResult)</TD></TR>
<TR><TD ALIGN="LEFT" >+ listBuildings(): List&lt;Buildable&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listResources(): List&lt;Resource&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ loadGame()</TD></TR>
<TR><TD ALIGN="LEFT" >+ reset()</TD></TR>
<TR><TD ALIGN="LEFT" >+ rollDx(roll: Roll): OutcomeType</TD></TR>
<TR><TD ALIGN="LEFT" >+ saveGame()</TD></TR>
<TR><TD ALIGN="LEFT" >+ showBuildables(): List&lt;CraftingPlan&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ start(deck: CardDeck)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PersistenceWriter1052887806[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)PersistenceWriter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ write(state: GameState)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

SerializationFilePersistor1997518945[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SerializationFilePersistor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   path: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ path(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ read(): GameState</TD></TR>
<TR><TD ALIGN="LEFT" >+ write(state: GameState)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

'edges    
Game1052887806 -> PersistenceWriter1052887806[label="saver
[0..1]"];
PersistenceWriter1052887806 -> SerializationFilePersistor1997518945[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml